sub_odom_topic_name: /odometry/filtered
sub_pitot_topic_name: /droni_sensors/pitot_pressure
sub_accel_topic_name: /droni_sensors/angular_accel_filtered
pub_estimated_wind_topic_name: /wind_speed/filtered_hybrid
sub_nn_estimator_topic_name: /wind_speed/filtered_nn
process_covariance: [1.0e-4, 1.0e-4, 5.0e-7]
measurement_covariance: [40.96, 40.96, 40.96,40.0,40.0,40.0]
initial_covariance: [0.09, 0.09, 1.0e-8]
initial_state: [0.0,0.0,0.77]
lambda_rdot: 0.0